timeout: 5
wallpaper: boot():/background.png

/Gentoo Linux (Custom Kernel)
	protocol: linux
	kernel_path: boot():/kernel-6.12.8-cachyos-6.12.8-lc
	kernel_cmdline: root=LABEL=GENROOTV2 rw nvidia_drm.modeset=1 nvidia_drm.fbdev=0 zswap.enabled=1 zswap.compressor=zstd mitigations=off
	module_path: boot():/initramfs-6.12.8-cachyos-6.12.8-lc.img
	module_path: boot():/amd-uc.img

/Gentoo Linux (Dist Kernel)
	protocol: linux
	kernel_path: boot():/kernel-6.12.8-gentoo-dist
	kernel_cmdline: root=LABEL=GENROOTV2 rw nvidia_drm.modeset=1 nvidia_drm.fbdev=0 zwap.enabled=1 zswap.compressor=zstd mitigations=off
	module_path: boot():/initramfs-6.12.8-gentoo-dist.img
	module_path: boot():/amd-uc.img
